
export const godryColumn=['SO NAME', 'DO NAME', 'SALES AREA', 'RO CODE', 'RO NAME', 'SUPPLY LOCATION', 'PRODUCT', 'NO OF TANKS', 'TANKAGE', 'STOCK DATE/ TIME', 'STOCK AVAILABLE (L)', 'DEAD STOCK (L)', 'STOCK ON WHEEL AVAILABLE (L)', 'PENDING INDENT QUANTITY (L)', 'AVERAGE NOZZLE SALES (L)', 'INDENT EXECUTION TIME (HRS)', 'TRANSIT TIME (HRS)', 'STOCK SURVIVAL HOURS (HRS)', 'EXPECTED DRYOUT DATE/ TIME', 'STATUS CRITICAL']
export const outofstockColumn=['SO NAME', 'DO NAME', 'SALES AREA', 'DATE', 'RO CODE', 'RO NAME', 'PRODUCT', 'NO OF TANK', 'TOTAL HOURS STOCK OUT', 'POTENTIAL LOSS (IN LITERS)', 'STOCK OUT HOURS - CUR MONTH', 'POTENTIAL LOSS - CUR MONTH (IN LITERS)', 'STOCK OUT HOURS - PREVIOUS MONTH', 'POTENTIAL LOSS - PREVIOUS MONTH (IN LITERS)']
export const romobileColumn=['Mobile Number', 'Ship-To Party', 'Sales Office', 'Distribution Channel', 'DifferReferCode', 'Mobile Type', 'Name 1', 'City', 'Description', 'Created By', 'Created On', 'Time', 'E-Mail Address']
export const rolistColumn=['Ship2Party', 'Name', 'SOff', 'Rg']
export const yv26Column=['Rec Code', 'Receiver', 'Document', 'DispMatDoc', 'DispItem', 'DispStLoc', 'RecvMatDoc', 'RecvItem', 'RecvStLoc', 'PGI Date', 'Batch', 'MatCode', 'MoT', 'InvoiceNo', 'AssignNo', 'Volume(KL)', 'Volume(K15)', 'Volume(K29)', 'Volume(TO)', 'Qty(EA)', 'State']
export const yv208Column=['Exception', 'Material', 'Shipment', 'ShpStatus', 'Vehicle', 'Ship2Party', 'Name', 'Delivery', 'Quantity', 'Sales Unit', 'Delivery quantity', 'Seal No', 'Invoice']
export const yv209dColumn=['Exception', 'DelCt', 'PRTY', 'Requested delivdate', 'Sales Document', 'Distribution Channel', 'Ship2Party', 'Name 1', 'RTD(in KM)', 'Material', 'OrderQty', 'Target quantity UoM', 'Truck no', 'Sales Group Desc', 'REMARKS', 'Sales Document Type', 'Sales Document Item', 'Created By', 'Sales Group']

export const Columns=[godryColumn,outofstockColumn,romobileColumn,rolistColumn,yv26Column,yv208Column,yv209dColumn]
export const tableName=['godry','outofstock','romobile','rolist','yv26','yv208','yv209d']